### ISSUE TITLE
Can't view Storage in a Chrome Extension

### ISSUE THREAD

**Issue by glittle** [weilueluo/storage-helper#2]
When attempting to view storage of an extension, get this:

`No permission to access chrome-extension://abcdihgbcbpemgkijlcabakpnjjochnl/`
`Cannot access non http/https webpage`

Can it be changed to also read for `chrome-extension://`?

**Comment by weilueluo** [comment]
Hi @glittle , unfortunately chrome does not allow extensions to access non-http/https pages.

ref: https://developer.chrome.com/docs/extensions/develop/concepts/match-patterns

**Comment by glittle** [comment]
I see. That's too bad. 

Thanks for the update!
